export const assets = [{url:"./la roca.jpeg", name: "rock"},
{url:"./cowboy.jpg", name: "gorro"},
{url:"./amogus.png", name: "sus"},
{url:"./caballero.png", name: "bolainas"},
{url:"./Twerk/am 1.PNG", name: "1"}, //llamado de una imagen dentro de una carpeta
{url:"./Twerk/am 2.PNG", name: "2"},
{url:"./Twerk/am 3.PNG", name: "3"},
{url:"./Twerk/am 4.PNG", name: "4"},
{url:"./Twerk/am 5.PNG", name: "5"},
{url:"./Escenas/fondo parque de diversiones.png", name: "fondo"},
{url:"./Escenas/piso parque de diversiones.png", name: "piso"},
{url:"./Escenas/tienda parque de diversiones.png", name: "tienda"},
{url:"./Escenas/escondite vacio.png", name: "basura"},
{url:"./Escenas/escondido.png", name: "escondido"},
{url:"./Escenas/cerca parque de diversiones.png", name: "cerca"},
{url:"./Escenas/lluvia y viento.jpg", name: "inicio1"},
];